
.Phony: install
install:
	echo "Building and installing SpringBoot Application with the Java Client"
	./mvnw clean install package -DskipTests

start:
	echo "Starting Spring Boot application "
	./mvnw spring-boot:run